import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import TokenButton from '@/components/blockchain/TokenButton'
import { Hydrate } from '@/components/utils/Hydrate'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hello Web3
        <w3m-button/>
        <Hydrate>
          <TokenButton/>
        </Hydrate>
      </main>
    </>
  )
}
